Changing instances of cluster name in PDO for cluster ID in fedramp e…
openshift/pagerduty-operator pull request #172
Opened 2022-03-03 16:31 UTC by luis-falcon

Changing instances of cluster name in PDO for cluster ID in fedramp environments

2022-03-03 20:08 UTC, jewzaam requested changes
Why not simply use the actual ID instead of name for all environments?  What is the value of having it be different?  The property set in the PD data is "ClusterID" so I'm surprised we use name.  Name is not unique and we shouldn't care about it.  The thing we care about is ID...

2022-03-03 20:37 UTC, sam-nguyen7 commented
> Why not simply use the actual ID instead of name for all environments? What is the value of having it be different? The property set in the PD data is "ClusterID" so I'm surprised we use name. Name is not unique and we shouldn't care about it. The thing we care about is ID...

@jewzaam I don't have a clear answer on this but I know that this was briefly discussed at the leads level and it was decided for only fedramp. cc @blrm 
https://coreos.slack.com/archives/C01M1NRKUF4/p1646142273310629?thread_ts=1646081822.790079&cid=C01M1NRKUF4

2022-03-03 20:50 UTC, jewzaam commented
> > Why not simply use the actual ID instead of name for all environments? What is the value of having it be different? The property set in the PD data is "ClusterID" so I'm surprised we use name. Name is not unique and we shouldn't care about it. The thing we care about is ID...
> 
> @jewzaam I don't have a clear answer on this but I know that this was briefly discussed at the leads level and it was decided for only fedramp. cc @blrm https://coreos.slack.com/archives/C01M1NRKUF4/p1646142273310629?thread_ts=1646081822.790079&cid=C01M1NRKUF4

Understood the ask is for fedramp only.  But there is a misalignment in the parameter to PD and the value passed.  And we should not care about the cluster name.  I don't see value in having this logic specific to fedramp unless someone can state why cluster name needs to remain for non-fedramp.

@blrm @luis-falcon thoughts?

2022-03-03 21:04 UTC, fahlmant commented
Just curious. what does the resulting PD service look like? Do you have a screenshot or something to share?

2022-03-03 21:05 UTC, luis-falcon commented
@jewzaam  The first changes I made had non of this logic. Just a simple replacement using the clusterID instead of the name for every environment. I am of the same opinion as you that just keeping the name for non fedramp and id for fedramp is just extra steps for nothing of real impact really. I  also do not see the need for the cluster name if we had the ID or to make a distinction  but I had discuss this with blair previously but apparently in lead talks this separation was decided so i just coded it this way. Would be nice to have the reasoning though :)

2022-03-03 21:12 UTC, blrm commented
I do agree that we should ultimately just move to cluster ID for everything. The reasoning for keeping this change scoped to only fedramp for now is explained in the JIRA card here: https://issues.redhat.com/browse/OSD-9561?focusedCommentId=19589360&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-19589360

Given the limited time we have to deliver the fedramp environment and the blast radius of swapping out all existing PD services for their Cluster ID replacements, we decided to just target fedramp initially and then move to cluster IDs for the whole fleet in a subsequent epic.

2022-03-03 21:26 UTC, sam-nguyen7 requested changes

2022-03-03 21:26 UTC, sam-nguyen7 commented on pkg/controller/pagerdutyintegration/clusterdeployment_created.go
>  	ClusterID := cd.Spec.ClusterName
```suggestion
	clusterID := cd.Spec.ClusterName
```

This variable shouldn't be exported.

2022-03-03 21:26 UTC, sam-nguyen7 commented on pkg/controller/pagerdutyintegration/clusterdeployment_deleted.go
>  	ClusterID := cd.Spec.ClusterName
```suggestion
	clusterID := cd.Spec.ClusterName
```
This variable shouldn't be exported.

2022-03-04 14:16 UTC, jewzaam commented
Following up in JIRA, thanks for the link and replies.

2022-03-04 15:24 UTC, luis-falcon commented on pkg/controller/pagerdutyintegration/clusterdeployment_created.go
>  	ClusterID := cd.Spec.ClusterName
good catch sam. thanks

2022-03-22 20:35 UTC, sam-nguyen7 reviewed
/lgtm
@luis-falcon any troubles with testing this before we merge?

2022-03-22 20:36 UTC, sam-nguyen7 approved these changes

2022-03-25 18:49 UTC, blrm commented
@luis-falcon  If testing for this one went well, this looks good to me. @jewzaam Could you PTAL? Thanks!

2022-03-28 14:52 UTC, jewzaam commented
/approve

2022-03-28 15:07 UTC, merged