Update ConfigMap EscalationPolicyID data field on reconcile
openshift/pagerduty-operator pull request #195
Opened 2022-07-12 12:25 UTC by supreeth7

Relates to: [OSD-12385](https://issues.redhat.com/browse/OSD-12385)
<hr>

- Currently, for existing PagerDuty services, the PD ConfigMaps do not have the `EscalationPolicyID` data field. The newly created service ConfigMaps have it.
- This is necessary to detect when there is a change in the PagerDutyIntegration escalation policy, compare it with the existing ConfigMap escalation policy, update the service and reconcile.
- This PR adds a feature to update the existing PD ConfigMaps to reflect the `EscalationPolicyID` data field for existing services on reconcile.

2022-07-12 17:30 UTC, jewzaam requested changes
/hold

PDIEscalationPolicyID vs EscalationPolicyID in Data struct is very hard to follow.
This PR changes EscalationPolicyID to be loaded from the CM and is used to check if there needs to be an update.  Furthermore, on CM load the PDIEscalationPolicyID is not set.  Any CM that has missing ESCALATION_POLICY_ID key will never have PDIEscalationPolicyID set and therefore will never get ESCALATION_POLICY_ID set.

1. Consolidate on use of single EscalationPolicyID as it is not possible to know what is happening without tracking through a lot of logic.
2. Add unit tests to cover the bug you are fixing.  Make sure the test reproduces the bug before you fix it.
3. Add unit tests to cover additional cases that might make sense for missing or unexpected values.

2022-07-13 10:48 UTC, supreeth7 commented
I agree, even though I was having a hard time trying to differentiate and track the two separate escalation policies.
I have made the appropriate changes and updated the description to reflect the same.
@jewzaam can you please give this another look? Thanks.

2022-07-14 10:39 UTC, supreeth7 commented on pkg/pagerduty/service.go
> -
I left the aspect of code modularity out of the window on this one, thanks for bringing it up.

2022-07-14 10:54 UTC, supreeth7 commented
Did a sanity check on a staging cluster, with the changes in https://github.com/supreeth7/pagerduty-operator/pull/1 merged, everything is working as expected.

2022-07-14 12:06 UTC, jewzaam commented
Thank you @supreeth7, looks great.

/hold cancel
/lgtm

2022-07-14 12:10 UTC, merged